print(1 + 1)
print("1 + 1")
print('a' + 'b')

print('1', type('1'))
print(int('1'), type(int('1')))
print(int('1') + 1)
print(float('1.2') + 1)
print(type(float('1.2') + 1))
print(bool(''))
print(bool('a'))
print(str(11) + 'b')